// Code generated by Tester Agent. DO NOT EDIT.
// Task: Chat UI Phase 2 — ChatToolbar component tests
// Builder must make these tests pass without modification.

import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/svelte";
import userEvent from "@testing-library/user-event";
import { fireEvent } from "@testing-library/svelte";
import ChatToolbar from "./ChatToolbar.svelte";

// ---------------------------------------------------------------------------
// Presence and data-testid
// ---------------------------------------------------------------------------

describe("ChatToolbar — presence", () => {
  it("should have data-testid='chat-toolbar'", () => {
    render(ChatToolbar, {
      props: {
        onLoadJson: vi.fn(),
        onExportJson: vi.fn(),
        onNewChat: vi.fn(),
      },
    });

    expect(screen.getByTestId("chat-toolbar")).toBeInTheDocument();
  });

  it("should render Load JSON button", () => {
    render(ChatToolbar, {
      props: {
        onLoadJson: vi.fn(),
        onExportJson: vi.fn(),
        onNewChat: vi.fn(),
      },
    });

    expect(screen.getByTestId("chat-load-json")).toBeInTheDocument();
  });

  it("should render Export JSON button", () => {
    render(ChatToolbar, {
      props: {
        onLoadJson: vi.fn(),
        onExportJson: vi.fn(),
        onNewChat: vi.fn(),
      },
    });

    expect(screen.getByTestId("chat-export-json")).toBeInTheDocument();
  });

  it("should render New Chat button", () => {
    render(ChatToolbar, {
      props: {
        onLoadJson: vi.fn(),
        onExportJson: vi.fn(),
        onNewChat: vi.fn(),
      },
    });

    expect(screen.getByTestId("chat-new-chat")).toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// Callbacks
// ---------------------------------------------------------------------------

describe("ChatToolbar — callbacks", () => {
  it("should call onExportJson when Export JSON is clicked", async () => {
    const onExportJson = vi.fn();
    const user = userEvent.setup();

    render(ChatToolbar, {
      props: {
        onLoadJson: vi.fn(),
        onExportJson,
        onNewChat: vi.fn(),
      },
    });

    await user.click(screen.getByTestId("chat-export-json"));

    expect(onExportJson).toHaveBeenCalledOnce();
  });

  it("should call onNewChat when New Chat is clicked", async () => {
    const onNewChat = vi.fn();
    const user = userEvent.setup();

    render(ChatToolbar, {
      props: {
        onLoadJson: vi.fn(),
        onExportJson: vi.fn(),
        onNewChat,
      },
    });

    await user.click(screen.getByTestId("chat-new-chat"));

    expect(onNewChat).toHaveBeenCalledOnce();
  });
});

// ---------------------------------------------------------------------------
// Load JSON file picker
// ---------------------------------------------------------------------------

describe("ChatToolbar — Load JSON file picker", () => {
  it("should have a hidden file input for loading JSON", () => {
    const { container } = render(ChatToolbar, {
      props: {
        onLoadJson: vi.fn(),
        onExportJson: vi.fn(),
        onNewChat: vi.fn(),
      },
    });

    const fileInput = container.querySelector('input[type="file"]');
    expect(fileInput).toBeInTheDocument();
  });

  it("should call onLoadJson with parsed JSON when a valid file is selected", async () => {
    const onLoadJson = vi.fn();

    const { container } = render(ChatToolbar, {
      props: {
        onLoadJson,
        onExportJson: vi.fn(),
        onNewChat: vi.fn(),
      },
    });

    const fileContent = JSON.stringify({ nodes: [], connections: [] });
    const file = new File([fileContent], "flow.json", {
      type: "application/json",
    });

    const fileInput = container.querySelector(
      'input[type="file"]',
    ) as HTMLInputElement;

    // Simulate file selection
    fireEvent.change(fileInput, { target: { files: [file] } });

    // Wait for FileReader to complete
    await new Promise((resolve) => setTimeout(resolve, 50));

    expect(onLoadJson).toHaveBeenCalledOnce();
    expect(onLoadJson).toHaveBeenCalledWith({ nodes: [], connections: [] });
  });
});

// ---------------------------------------------------------------------------
// Accessibility
// ---------------------------------------------------------------------------

describe("ChatToolbar — accessibility", () => {
  it("Load JSON button should have an accessible name", () => {
    render(ChatToolbar, {
      props: {
        onLoadJson: vi.fn(),
        onExportJson: vi.fn(),
        onNewChat: vi.fn(),
      },
    });

    expect(screen.getByTestId("chat-load-json")).toHaveAccessibleName();
  });

  it("Export JSON button should have an accessible name", () => {
    render(ChatToolbar, {
      props: {
        onLoadJson: vi.fn(),
        onExportJson: vi.fn(),
        onNewChat: vi.fn(),
      },
    });

    expect(screen.getByTestId("chat-export-json")).toHaveAccessibleName();
  });

  it("New Chat button should have an accessible name", () => {
    render(ChatToolbar, {
      props: {
        onLoadJson: vi.fn(),
        onExportJson: vi.fn(),
        onNewChat: vi.fn(),
      },
    });

    expect(screen.getByTestId("chat-new-chat")).toHaveAccessibleName();
  });

  it("all three toolbar buttons should be focusable", () => {
    render(ChatToolbar, {
      props: {
        onLoadJson: vi.fn(),
        onExportJson: vi.fn(),
        onNewChat: vi.fn(),
      },
    });

    const buttons = [
      screen.getByTestId("chat-load-json"),
      screen.getByTestId("chat-export-json"),
      screen.getByTestId("chat-new-chat"),
    ];

    for (const button of buttons) {
      expect(button).not.toBeDisabled();
      button.focus();
      expect(document.activeElement).toBe(button);
    }
  });
});
