/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/components/flowgraph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get component flow graph
         * @description Returns the complete flow graph with nodes and edges
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Flow graph with nodes and edges */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components/status/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get component status
         * @description Returns detailed status for a specific component instance
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Component instance name */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Component status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Component not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available component types
         * @description Returns array of component metadata including schemas
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of component types */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ComponentType"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components/types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get component type by ID
         * @description Returns metadata and schema for a specific component type
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Component type ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Component type metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ComponentType"];
                    };
                };
                /** @description Component type not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate component flow connectivity
         * @description Performs flow graph connectivity analysis
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Flow connectivity analysis results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ComponentType: {
            /** @description Component category */
            category?: string;
            /** @description Component description */
            description?: string;
            /** @description Business domain (robotics, semantic, etc.) */
            domain?: string;
            /** @description Component ID */
            id: string;
            /** @description Human-readable name */
            name: string;
            /** @description Technical protocol (udp, tcp, etc.) */
            protocol?: string;
            /** @description Component configuration schema */
            schema?: components["schemas"]["websocket_input.v1"] | components["schemas"]["json_generic.v1"] | components["schemas"]["json_filter.v1"] | components["schemas"]["objectstore.v1"] | components["schemas"]["graph-processor.v1"] | components["schemas"]["file.v1"] | components["schemas"]["httppost.v1"] | components["schemas"]["websocket.v1"] | components["schemas"]["udp.v1"] | components["schemas"]["json_map.v1"] | components["schemas"]["context-processor.v1"];
            /** @description Component type (input/processor/output/storage) */
            type: string;
            /** @description Component version */
            version?: string;
        };
        /**
         * websocket_input Configuration
         * @description WebSocket input for receiving federated data from remote StreamKit instances
         */
        "websocket_input.v1": Record<string, never>;
        /**
         * json_generic Configuration
         * @description Wraps plain JSON into GenericJSON (core .json.v1) format
         */
        "json_generic.v1": Record<string, never>;
        /**
         * json_filter Configuration
         * @description GenericJSON (core .json.v1) filter for field-based filtering
         */
        "json_filter.v1": Record<string, never>;
        /**
         * objectstore Configuration
         * @description NATS ObjectStore component for immutable message storage
         */
        "objectstore.v1": Record<string, never>;
        /**
         * graph-processor Configuration
         * @description Graph processor for entity extraction and storage
         */
        "graph-processor.v1": Record<string, never>;
        /**
         * file Configuration
         * @description File output for writing messages to disk in JSON, JSONL, or raw format
         */
        "file.v1": Record<string, never>;
        /**
         * httppost Configuration
         * @description HTTP POST output for sending messages to HTTP endpoints with retries
         */
        "httppost.v1": Record<string, never>;
        /**
         * websocket Configuration
         * @description WebSocket output component for real-time visualization and data streaming
         */
        "websocket.v1": Record<string, never>;
        /**
         * udp Configuration
         * @description UDP input component for receiving MAVLink and other UDP data
         */
        "udp.v1": Record<string, never>;
        /**
         * json_map Configuration
         * @description GenericJSON (core .json.v1) field transformer for renaming, adding, and removing fields
         */
        "json_map.v1": Record<string, never>;
        /**
         * context-processor Configuration
         * @description Context processor for derived state computation and complex rules
         */
        "context-processor.v1": Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
